// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjaqzqauwjdfayoltcsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqYXF6cWF1d2pkZmF5b2x0Y3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwOTA4NTIsImV4cCI6MjA1MjY2Njg1Mn0.3RNaQmQRp0X3qN5tmofr4tXQBNsLCfSqfuTwH2-5h30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);